### PR TITLE
Player die/respawn using checkpoints

### LINKED ISSUE #97: Death and respawn sequence

### PR DESCRIPTION
**Pull request by razcore-art**
Build on guilhermehto's work with checkpoints. Checkpoints node is under
the Game node and keeps track of visited checkpoints. I've simplified it
though, it's just a list of checkpoints because we don't use the other
functinality yet and it's just easier to do incremental changes rather
than think about everything from start, such as menu for fast-travel
etc.

I've added a "debug" key (Q) to trigger death so I can check the
functionality.

**This is WIP and it will most likely break stuff, has to be merged
after #127**

closes #97

### CODE REVIEW

**Comment by razcore-art** [comment]
Known issues:
- [ ] only death animation plays when player touches wall(?) or ledge possibly
- [ ] checkpoints need to be saved/loaded when changing level since they're part of the level, otherwise the assertion check fails since the visited checkpoints are kept in the Game scene

**Comment by NathanLovato** [comment]
Did you forget to push transition.gd in the previous PR? I can't find it in the project, had to fix the scenes as itś marked as a missing dependency

**Comment by razcore-art** [comment]
No, I didn't forget anything, this PR & #127 are based on branches from the same commit so they have breaking changes that need to be fixed in the scene files. I wanted to understand the merge conflict problem with a practical example. #127 includes `Transition.gd` + changes in the `Game` scene to use `Transition.gd`, this PR doesn't. In any case I just checked yesterday that now with the name changes I got more conflicts than I bargained for so this branch needs a bit of fixing.

**Comment by NathanLovato** [comment]
Try `git pull --rebase upstream master` if you set this repo as the upstream. As git detect file renames, it can rename your local files and treat your changes like they're using the new file structure. Should save you some refactoring. I can give you a hand as well

**Comment by NathanLovato** [comment]
Manually merged as 0320dcf9d1fdda886e3292dafeb371ac4bc9fc11

There's a bug with respawn after merging, I'll open an issue for it

**Pull request closed without merging**
