### PR TITLE
[WIP] Level loops

### LINKED ISSUE #8: Prototype: design level loops
See [the prototype description](https://github.com/GDquest/godot-metroidvania-2d/blob/master/GAME_CONCEPT.org#design-level-loops) in the game concept.

This is design work. The idea is to test the current motion, see where it fails and to find ways to improve it. I.e. right now hooking going down doesn't work. Could you do some level design experiments? Create small chunks, think about a few obstacles to start fleshing out the game's feel?

I'm not hoping for a polished result at this point, but rather atomic loops we can combine together to build interesting rooms (or maybe do procedural generation?! 😉)

### PR DESCRIPTION
**Pull request by henriiquecampos**
I started working on some level loops to close #8 and I went with an ability test approach.

We can already make some cool challenges stacking and matching them:

005 - Demo

### CODE REVIEW

**Comment by NathanLovato** [comment]
Thanks! You don't have to detail each level design block, they should be self-explanatory

**Comment by NathanLovato** [comment]
Also, as I've said before, I'd like you to test the hook before adding new mechanics (e.g. moving hooking points). When we talk about loops in level design, they're the smallest building blocks of levels, e.g. two platforms with a gap that's small enough to jump over, two platforms with a gap that's too far to reach, but there's a hooking point, etc. Like legos, the basic blocks you combine and replicate to make levels.

There should be plenty to explore with the game's core before adding new behaviors.

**Comment by henriiquecampos** [comment]
Alright, just broke them into more atomic-ish modules and updated the PR :grin:

**Comment by NathanLovato** [comment]
Thanks, just checked the PR, two things:

- You should use the grid over guides, much more efficient to snap to. If we change any value like the speed of the char, which is likely to happen, all guides will be off.
- Is there a scene where I can test the level chunks? Just in case it isn't clear, the idea is to build great, small level bits, and to extract the most interesting level loops/patterns off that. But as with any design work, you want to start with sketches, with actual levels. So you don't have to build these tiny scenes as you go: I just meant I'm looking for you to focus your attention on that, figuring out the interesting ways in which we can use the hook.

As I think I've written in the prototype, this is level design work first and foremost: right now you're coding new obstacles or tools for the level designer before you've exhausted the possibilities of the most basic ones. I can create quite a few complete frames/levels without a moving hook, void, etc. That's what I'd like you to do.

Adding mechanics before pushing the core and exploring possibilities through level design is a common mistake, and one I've consistently made with my first studio: I'd request Florian to give me lots of small building blocks (spikes, moving platforms, enemies, etc.) which took our attention away from the core controls and game feel, leading us to a so-so game in the end.

See http://www.ebog.com/html5.php?id=30747 for instance. The level design misses a lot of marks - I didn't have much experience at the time. (NB: the game starts at level 3, the first 2 are the tutorial - designed to run on old, small phones running android 2, with html5 canvas rendering, hence the small number of sprites, no particles, etc.)

**Comment by NathanLovato** [comment]
And don't take screenshots of every scene you design! I will review the project directly, please focus on level design work

**Comment by henriiquecampos** [comment]
>     * You should use the grid over guides, much more efficient to snap to. If we change any value like the speed of the char, which is likely to happen, all guides will be off.

I am, the guides are just references if I want to create inherited scenes. E.g. to see the difference between short and long versions of the same loop, I am not using them for snap.

>     * Is there a scene where I can test the level chunks? Just in case it isn't clear, the idea is to build great, small level bits, and to extract the most interesting level loops/patterns off that. But as with any design work, you want to start with sketches, with actual levels. So you don't have to build these tiny scenes as you go: I just meant I'm looking for you to focus your attention on that, figuring out the interesting ways in which we can use the hook.

I was testing in `Game.tscn` but didn't commit changes on it. I will create a `Playground.tscn` to put them together.

**Comment by NathanLovato** [comment]
Great idea with the guides, that's a smart way to use them!
And all good, I'm looking forward to testing the scene :smile:

**Comment by henriiquecampos** [comment]
I just opened the PR for review and squashed everything.

**Comment by NathanLovato** [comment]
Thanks :)

**Pull request merged**
