### PR TITLE
Add PullableObject

### PR DESCRIPTION
**Pull request by henriiquecampos**
~~Hopefully~~ Close #47 
Currently I added only the PullableObject, trying to achieve only a part of the problem presented in #34 as by now the Player can't pull itself to said object.

I went with a `RigidBody2D` approach, as suggested, but is noticeable that the `Player` won't be able to use said `PullableObject` as, e.g., part of the environment, jumping on it for instance.

### CODE REVIEW

**Comment by NathanLovato** [comment]
There's not much to comment on for now. As I said in #44 the priority is game feel. I can't judge the code structure before we can test the mechanic.

Design-wise, I see you're going with a link with the object that you can toggle on and off. With how the game feels and plays fast right now, I'd make it more like a one-shot action that breaks an object instead of cutting the flow of the game: have the pull action put the character on hold for an instant, pull the obstacle away, get it flying, so that the character can move forward.

Code-wise, I'm not sure the pull ray shouldn't handle pulling the target object. The hook already has a forward-facing raycast and logic to detect targets. Right now you're handling the same input in a new script, it'll make harder to track the code's flow. But again, not sure, it'll depend on the game design.

> the Player can't pull itself to said object

Just in case there'd be a misunderstanding: this task is about pulling the object with the hook, towards the player, or out of the way.

**Comment by henriiquecampos** [comment]
I've update the whole logic to make it feel more interesting. RigidBody2Ds are not very reliable, so I went for a KinematicBody2D approach.

But I found a bug: when stacking 2 of these object on top of each other the top one stops falling. It doesn't seem to be anything related to what I've implemented, I have tested and from the lines I use to control the gravity none reflects the bug. I tried to comment all of them, and still nothing. :confused:

**Comment by henriiquecampos** [comment]
> Code-wise, I'm not sure the pull ray shouldn't handle pulling the target object. The hook already has a forward-facing raycast and logic to detect targets. Right now you're handling the same input in a new script, it'll make harder to track the code's flow. But again, not sure, it'll depend on the game design.

I chose to avoid messing with what is already working and instead create a new class. I think the input issue is not a problem, as in any case they would be fired together.

>I'd make it more like a one-shot action that breaks an object instead of cutting the flow of the game: have the pull action put the character on hold for an instant, pull the obstacle away, get it flying, so that the character can move forward.

I really didn't understand what you mean here. They are meant to break or to be pulled by the hook?

In the first case it would be easier to just disable the collision shape and play a "break" animation.

Should this be just a "cutscene-ish" action? Like: 
- you throw the hook
- it collides with a pullable object
- player loses control over the character
- the object is thrown away

Just like a lock-key mechanic?

**Comment by NathanLovato** [comment]
I did a checkout to your branch. Currently, it prevents from hooking as I expected, as your new raycast consumes all input events.

Then, as I said, game feel should come first. Right now, the mechanic doesn't feel good. You keep the button down to slowly pull the object towards the player, as if it wasn't affected by the world's physics:

- It's slow
- It can go flying weirdly above the hook line
- It doesn't feel playful, satisfying, or fun

It completely missed the task. From #34:

> The idea is to have obstacles that act as *one-time hookable points so that the player has only one chance to reach a given platform, or has to pick a path mid air to reach one of several targets*.

I think the description was pretty clear. When I reviewed the PR yesterday:

> With how the game feels and plays fast right now, I'd make it more like a one-shot action that breaks an object instead of cutting the flow of the game: have the pull action put the character on hold for an instant, pull the obstacle away, get it flying, so that the character can move forward.

I don't think we can reuse the code from this PR. I think I'll tackle this task.

**Pull request closed without merging**
