### PR TITLE
[WIP] Add BasicMovementLevel

### PR DESCRIPTION
**Pull request by henriiquecampos**
Alright, so I just started working on the first level for #24 I tried to answer the follow questions to the player:

- What is the Walk speed
- What can I aim at
- What happens if I shoot on a target
- What is the hook range
- What is the jump height
- When should I jump
- When should I hook instead

Tho I feel `when should I jump` still misses something, I was thinking about some platform + falling, but this would break the idea of "favoring the hook".

How can I approach that the jump is also useful, even when there are hook targets?

image

### CODE REVIEW

**Comment by guilhermehto** [comment]
> How can I approach that the jump is also useful, even when there are hook targets?

The only thing that comes to mind is making the player have to jump to be able to reach a hooking target. 

I liked the map, had only two problems:

1. Wasn't sure which way I should head first
2. There were too many hooking targets, I believe if you remove some of them the movement will feel more fluid. Take the bottom part of the right corner as an example, only one target per "hole" would be enough, I think.

Also found a bug #92 while testing :laughing: 

Can't really think of anything else :thinking:

**Comment by henriiquecampos** [comment]
> Wasn't sure which way I should head first

If the player already knows the basics they can go to the left straight (because it needs to know how to jump and hook), otherwise to the right, to learn such movements.

> There were too many hooking targets, I believe if you remove some of them the movement will feel more fluid. Take the bottom part of the right corner as an example, only one target per "hole" would be enough, I think.

Yeah I think I can remove the one in the middle, but the idea is to make the player try to hook in mid-air. Can we teach that with a single target? Maybe if I decrease the gap between them and just add a small 1x4 wall instead of this 3x4?

**Comment by NathanLovato** [comment]
To me, it feels and looks bad overall.

Gameplay-wise, the first jumps are already easy to miss, making start of the level frustrating and harder than the following part. You can go left and do the level the other way around from the start, and I can see you tried to make a loop to get a metroidvania sense, but if an area has a given objective (teaching the player basic moves), you should focus solely on that, and not on allowing the player to backtrack. No need to offer branching paths either, especially if one is clearly way easier/more accessible than the other.
The area where you hang from the ceiling is a sudden difficulty spike.

The visual layout of a level matters a lot. Just like with graphic design in general, you want to guide the player's eye by drawing clear paths. Right now it's not the case.

At this point, I think we should get help from a level designer, and get an artist on board. Now I've tried and you've tried as well, it's clear to me our time will be better spent in areas where we have more experience.

**Comment by NathanLovato** [comment]
Nothing against you by the way, I mean it when I say we all lack experience. And I'd like the level design and the art to match the care and quality we can offer with the code. Because it's taken a lot of work on that side already

**Comment by henriiquecampos** [comment]
> No need to offer branching paths either, especially if one is clearly way easier/more accessible than the other.

I thought that it would be annoying to force players that are already skilled to pass through a tutorial-ish level, going to the left and skipping this level, since the left path could connect to another level instead of having a wall.

Anyway, since there won't be further iterations on it, I will close the PR.

**Pull request closed without merging**
